### PR TITLE
Updates to use spring-boot-starter-parent.

### PR DESCRIPTION
**Pull request by spencergibb**
Rather than spring-cloud-build. This eliminates some potential weirdness in using the thing we're building.

This should only be merged after Hoxton.SR7

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
With this change we won't be able to publish docs to docs spring io, nor will we generate a merged readme. We can copy the required parts of pom from sc build though

**Comment by spencergibb** [comment]
I figured there would be parts I missed

**Comment by marcingrzejszczak** [comment]
Why not just upgrade to the latest stable GA version of spring cloud ?

**Comment by spencergibb** [comment]
:man_shrugging: I think that's what ryan did.

**Pull request closed without merging**
